on: workflow_dispatch

env:
  image_go: golang:1.19.2-alpine3.16
  protoc_gen_go_version: 1.28
  protoc_gen_go_grpc_version: 1.2
  registry: ghcr.io
  tag: latest

jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - name: repo checkout
        uses: actions/checkout@v3

      - name: buildx installation
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker build
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            IMAGE_GO=${{ env.image_go }}
            PROTOC_GEN_GO_VERSION=${{ env.protoc_gen_go_version }}
            PROTOC_GEN_GO_GRPC_VERSION=${{ env.protoc_gen_go_grpc_version }}
          tags: ${{ env.registry }}/${{ github.repository }}:${{ env.tag }}
          push: true
